name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
        
          # Your ML workflow
          pip install -r requirements.txt
          python3 train.py

          echo "MODEL METRICS"
          cat metrics.txt
